apiVersion: kapro.io/v1alpha1
kind: MemberCluster
metadata:
  name: canary-eu
  labels:
    kapro.io/tier: canary
    kapro.io/region: europe-west3
spec:
  actuator:
    mode: pull
    backend: flux
    pull:
      ociRepository: app-bundle
      namespace: flux-system

