apiVersion: kapro.io/v1alpha1
kind: MemberCluster
metadata:
  name: prod-eu
  labels:
    kapro.io/tier: production
    kapro.io/region: europe-west3
spec:
  delivery:
    mode: pull
    backendRef: argo
    parameters:
      namespace: argocd
      applicationSelector.pos-server: service=pos-server,region=europe-west3
      applicationSelector.sdc: service=sdc,region=europe-west3
      applicationSelector.keycloak: service=keycloak,region=europe-west3
