apiVersion: kapro.io/v1alpha1
kind: MemberCluster
metadata:
  name: prod-us
  labels:
    kapro.io/tier: production
    kapro.io/region: us-central1
spec:
  delivery:
    mode: pull
    backendRef: argo
    parameters:
      namespace: argocd
      applicationSelector.pos-server: service=pos-server,region=us-central1
      applicationSelector.sdc: service=sdc,region=us-central1
      applicationSelector.keycloak: service=keycloak,region=us-central1
