apiVersion: kapro.io/v1alpha1
kind: Pipeline
metadata:
  name: checkout-progressive
spec:
  stages:
    - name: canary
      selector:
        matchLabels:
          kapro.io/tier: canary
    - name: production-eu
      selector:
        matchLabels:
          kapro.io/tier: production
          kapro.io/region: europe-west3
      dependsOn:
        - stage: canary
          requiredSoakTime: 30m
          strategy: all
      gate:
        mode: manual
        approval:
          required: true
          approvers: ["sre-team"]
    - name: production-global
      selector:
        matchLabels:
          kapro.io/tier: production
      strategy:
        maxParallel: 10
      dependsOn:
        - stage: production-eu
          requiredSoakTime: 1h
          strategy: all

