apiVersion: kapro.io/v1alpha1
kind: Release
metadata:
  name: checkout-v1-2-3
spec:
  version: "5.28.0"
  versions:
    keycloak: "26.2.5"
  pipelines:
    - name: main
      pipeline: checkout-progressive
  suspended: false
  timeout: 4h
