apiVersion: kapro.io/v1alpha1
kind: KaproBundle
metadata:
  name: checkout
spec:
  registries:
    - name: gar
      url: oci://europe-west3-docker.pkg.dev/my-project/charts
      provider: gcp
      interval: 5m
  components:
    - name: pos-server
      version: "5.28.0"
      repo: gar
      targetNamespace: workloads
    - name: sdc
      version: "5.28.0"
      repo: gar
      targetNamespace: workloads
    - name: keycloak
      version: "26.2.5"
      repo: gar
      targetNamespace: workloads
      shared: true
      prune: false
  defaults:
    timeout: 10m
    retries: 3

